# Generated by Django 4.0.5 on 2022-07-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_comment_comment_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='game',
            new_name='product',
        ),
    ]
