# Generated by Django 4.0.5 on 2022-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_rename_game_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
