# Generated by Django 4.0.5 on 2022-07-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_comment_rating'),
        ('Product', '0005_product_product_picture'),
    ]

    operations = [
    ]
