# Generated by Django 4.0.5 on 2022-07-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_merge_20220726_1823'),
        ('Product', '0006_product_product_file'),
    ]

    operations = [
    ]
