# Generated by Django 4.0.5 on 2022-07-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_comment_rating'),
        ('Product', '0008_alter_comment_rating_alter_product_hoehlen_and_more'),
    ]

    operations = [
    ]
