# Generated by Django 4.0.6 on 2022-07-28 14:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hoehlen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockwerke',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'White'), ('#000000', 'Black'), ('#696969', 'Gray'), ('#A67133', 'Brown'), ('#FF0000', 'Red'), ('#FF8C00', 'Orange'), ('#FFFF00', 'Yellow'), ('#228B22', 'Green'), ('#00FFFF', 'Cyan'), ('#00BFFF', 'Blue'), ('#8A2BE2', 'Purple'), ('#FF00FF', 'Pink')], default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
