# Generated by Django 4.0.6 on 2022-07-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_merge_20220727_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
