# Generated by Django 4.0.6 on 2022-07-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_rating_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
