# Generated by Django 4.0.6 on 2022-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_product_rating_product_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
