# Generated by Django 4.0.5 on 2022-07-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(null=True, upload_to='product_files/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='product_pictures/'),
        ),
    ]
