# Generated by Django 4.0.5 on 2022-07-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_color'),
        ('Product', '0015_alter_product_product_file_and_more'),
    ]

    operations = [
    ]
