# Generated by Django 4.0.5 on 2022-07-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_merge_20220728_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hoehlen',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stockwerke',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
