# Generated by Django 4.0.5 on 2022-07-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_merge_20220728_1250'),
        ('Product', '0018_remove_product_product_file_alter_product_color_and_more'),
    ]

    operations = [
    ]
