# Generated by Django 4.0.5 on 2022-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_remove_product_product_file_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
