# Generated by Django 4.0.5 on 2022-07-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_comment_reported'),
        ('Product', '0019_merge_20220728_1916'),
    ]

    operations = [
    ]
