# Generated by Django 4.0.5 on 2022-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_merge_0019_comment_reported_0019_merge_20220728_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='product_pictures/'),
        ),
    ]
