# Generated by Django 4.0.5 on 2022-07-28 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_merge_20220728_1915'),
        ('Product', '0020_merge_0019_comment_reported_0019_merge_20220728_1927'),
        ('Product', '0021_alter_product_product_picture'),
    ]

    operations = [
    ]
