# Generated by Django 4.0.5 on 2022-07-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_merge_20220728_2120'),
        ('Product', '0022_merge_20220728_2136'),
    ]

    operations = [
    ]
