# Generated by Django 4.0.6 on 2022-07-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_merge_20220728_2101'),
        ('Product', '0023_merge_20220728_2201'),
    ]

    operations = [
    ]
