# Generated by Django 4.0.6 on 2022-07-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_merge_20220728_2223'),
        ('Product', '0024_merge_20220728_2238'),
    ]

    operations = [
    ]
