# Generated by Django 4.0.6 on 2022-07-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_merge_20220728_2244'),
        ('Product', '0026_alter_product_price'),
    ]

    operations = [
    ]
