# Generated by Django 4.0.5 on 2022-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Useradmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favourite_cat',
            field=models.CharField(default='bengal', max_length=100),
            preserve_default=False,
        ),
    ]
